# Generated by Django 4.2.2 on 2023-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='PetitModel_images/')),
                ('sujet', models.CharField(max_length=100)),
                ('texte', models.TextField()),
            ],
        ),
    ]
