# Generated by Django 4.2.2 on 2023-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rowgx70'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='partenaire_images/')),
            ],
        ),
    ]
