# Generated by Django 4.2.2 on 2023-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='professeurs_image/')),
            ],
        ),
    ]
